App.views.Viewport = Ext.extend(Ext.Panel, {
    fullscreen: true,
    layout: 'card',
    cardSwitchAnimation: 'slide',
    dockedItems: [
        {
        	xtype: 'toolbar',
        	title: 'Healthcare App',
        	items: [
    	        {
    	            text: 'Back',
    	            itemId: 'backBtn',
    	            ui: 'back',
    	        },
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{xtype: 'spacer'},
				{
    	            itemId: 'favoritesBtn',
					iconCls: 'favorites',
					iconMask: true,
    	            ui: 'action',
    	        },
				{xtype: 'spacer'},
				{
    	            itemId: 'home1Btn',
					iconCls: 'home',
					iconMask: true,
    	            ui: 'action',
    	        },
    	        {xtype: 'spacer'},
    	        {
    	            itemId: 'searchBtn',
    	            iconCls: 'search',
    	            iconMask: true,
    	            ui: 'action',
    	        },
    	    ],
        },
    ],
});